PassionProject-Nith/Controllers/AlbumsPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PassionProject_Nith.Data;
using PassionProject_Nith.Models;

namespace PassionProject_Nith.Controllers
{
    public class AlbumsPageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlbumsPageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AlbumsPage
        public async Task<IActionResult> Index()
        {
            return View(await _context.Albums.ToListAsync());
        }

        /* GET: Albums/Index 
         * sortOrder Function
         */
        [HttpGet("albums/index")]
        public IActionResult Index(string sortOrder)
        {
            var albums = _context.Albums.AsQueryable();

            if (sortOrder == "name")
            {
                albums = albums.OrderBy(a => a.AlbumTitle);
            }

            return View(albums.ToList());
        }

        // GET: Albums/Details
        public IActionResult Details(int id)
        {
            var album = _context.Albums
                .Include(a => a.Tracks)
                .FirstOrDefault(a => a.AlbumId == id);

            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        public IActionResult Create()
        {
            var artists = _context.Artists.ToList();
            ViewBag.ArtistSelectList = new SelectList(artists, "ArtistId", "ArtistName");
            return View(new Album());
        }


        // POST: Albums/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("AlbumTitle,Genre,ReleaseDate,ArtistId")] Album album)
        {

            if (album.ArtistId == 0)
            {
                ModelState.AddModelError("ArtistId", "Artist is required.");
            }
            else
            {
                var artist = await _context.Artists.FindAsync(album.ArtistId);
            }

            if (ModelState.IsValid)
            {
                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var artists = await _context.Artists.ToListAsync();
            ViewBag.ArtistSelectList = new SelectList(artists, "ArtistId", "ArtistName");

            return View(album);
        }


        // GET: Albums/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }

        // POST: Albums/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("AlbumId,AlbumTitle,Genre,ReleaseDate,ArtistId")] Album album)
        {
            if (id != album.AlbumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(album);
        }

        // GET: Albums/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.FirstOrDefaultAsync(m => m.AlbumId == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Albums/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Albums.FindAsync(id);
            _context.Albums.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

PassionProject-Nith/Controllers/ArtistsPageController.cs
using Microsoft.AspNetCore.Mvc;
using PassionProject_Nith.Data;
using Microsoft.EntityFrameworkCore;
using PassionProject_Nith.Models;

namespace PassionProject_Nith.Controllers
{
    public class ArtistsPageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArtistsPageController(ApplicationDbContext context)
        {
            _context = context;
        }

       // GET: ArtistsPage
       public async Task<IActionResult> Index()
        {
            return View(await _context.Artists.ToListAsync());
        }

        /* GET: artists/index
         * sortOrder Function
         */
        [HttpGet("artists/index")]
        public IActionResult Index(string sortOrder)
        {
            var artists = _context.Artists.AsQueryable();

            if (sortOrder == "name")
            {
                artists = artists.OrderBy(a => a.ArtistName);
            }

            return View(artists.ToList());
        }

        // GET: Artists/Details
        public IActionResult Details(int id)
        {
            var artist = _context.Artists
                .Include(a => a.Albums)
                .FirstOrDefault(a => a.ArtistId == id);

            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Artists/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ArtistName,ArtistBio")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(artist);
        }

        // GET: Artists/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ArtistId,ArtistName,ArtistBio")] Artist artist)
        {
            if (id != artist.ArtistId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(artist);
        }

        // GET: Artists/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FirstOrDefaultAsync(m => m.ArtistId == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

PassionProject-Nith/Controllers/TracksPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PassionProject_Nith.Data;
using PassionProject_Nith.Models;

namespace PassionProject_Nith.Controllers
{
    public class TracksPageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TracksPageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TracksPage
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tracks.ToListAsync());
        }

        // GET: Tracks/Create
        public IActionResult Create()
        {
            var albums = _context.Albums.ToList();
            ViewBag.AlbumSelectList = new SelectList(albums, "AlbumId", "AlbumTitle");
            return View();
        }

        // POST: Tracks/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("TrackTitle,TrackLength,AlbumId")] Track track)
        {

            if (ModelState.IsValid)
            {
                _context.Add(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var albums = await _context.Albums.ToListAsync();
            ViewBag.AlbumSelectList = new SelectList(albums, "AlbumId", "AlbumTitle");

            return View(track);
        }

        //GET: Tracks/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            var track = await _context.Tracks.FindAsync(id);
            if (track == null)
            {
                return NotFound();
            }

            if (track == null)
            {
                return NotFound();
            }
            return View(track);
        }

        //POST: Tracks/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("TrackId,TrackTitle,TrackLength,AlbumId")] Track track)
        {
            if (id != track.TrackId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(track);
        }

        // GET: Tracks/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = await _context.Tracks.FirstOrDefaultAsync(m => m.TrackId == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        // POST: Tracks/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var track = await _context.Tracks.FindAsync(id);
            _context.Tracks.Remove(track);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

PassionProject-Nith/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PassionProject_Nith</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PassionProject_Nith.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PassionProject_Nith</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArtistsPage" asp-action="Index">Artists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AlbumsPage" asp-action="Index">Albums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TracksPage" asp-action="Index">Tracks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PassionProject_Nith - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>